
#### ICD-10 Health Profile

This section compares exposure diagnoses group to population, which don't have the exposure. Section plots diagnoses which are more common.

```{r spiderplot, echo = FALSE}
renderPlot({
  health_profile(data_population = dpop(), data_diagnoses = diagnoses, exposure_icd10 = input$exposure_icd10, exposure_src = input$exposure_src )
})
```


#### Top ICD-10 Diagnoses

Diagnoses which has over 10 % gap between groups. Diagnoses are aggregated to 3 letters.

```{r topicd10, echo = FALSE}
tbl_comparison <- reactive({
  tbl_icd10_comparison(data_population_grouped = dpop(), data_diagnoses = diagnoses, exposure_icd10 = input$exposure_icd10, exposure_src = input$exposure_src)
})

renderPlot({
  plot_icd10_comparison(tbl_comparison())
})


DT::dataTableOutput("tbl_comparison_out")
output$tbl_comparison_out <- DT::renderDataTable( tbl_comparison() ,
                                                  options = list(
                                                    order = list(6, 'desc'),
                                                    rownames = F
                                                  ))
```

